DELETE FROM IzendaCountryCode
;#
INSERT INTO IzendaCountryCode (Name,Code2,Code3,Continent)
     VALUES ('Andorra','AD','AND','Europe'),
('United Arab Emirates','AE','ARE','Asia'),
('Afghanistan','AF','AFG','Asia'),
('Antigua and Barbuda','AG','ATG','North America'),
('Anguilla','AI','AIA','North America'),
('Albania','AL','ALB','Europe'),
('Armenia','AM','ARM','Asia'),
('Angola','AO','AGO','Africa'),
('Antarctica','AQ','ATA','Antarctica'),
('Argentina','AR','ARG','South America'),
('American Samoa','AS','ASM','Oceania'),
('Austria','AT','AUT','Europe'),
('Australia','AU','AUS','Oceania'),
('Aruba','AW','ABW','North America'),
('Åland Islands','AX','ALA','Europe'),
('Azerbaijan','AZ','AZE','Asia'),
('Bosnia and Herzegovina','BA','BIH','Europe'),
('Barbados','BB','BRB','North America'),
('Bangladesh','BD','BGD','Asia'),
('Belgium','BE','BEL','Europe'),
('Burkina Faso','BF','BFA','Africa'),
('Bulgaria','BG','BGR','Europe'),
('Bahrain','BH','BHR','Asia'),
('Burundi','BI','BDI','Africa'),
('Benin','BJ','BEN','Africa'),
('Saint Barthélemy','BL','BLM','America'),
('Bermuda','BM','BMU','North America'),
('Brunei Darussalam','BN','BRN','Asia'),
('Bolivia, Plurinational State of','BO','BOL','South America'),
('Bonaire, Sint Eustatius and Saba','BQ','BES','North America'),
('Brazil','BR','BRA','South America'),
('Bahamas','BS','BHS','North America'),
('Bhutan','BT','BTN','Asia'),
('Bouvet Island','BV','BVT','Antarctica'),
('Botswana','BW','BWA','Africa'),
('Belarus','BY','BLR','Europe'),
('Belize','BZ','BLZ','Central America'),
('Canada','CA','CAN','North America'),
('Cocos (Keeling) Islands','CC','CCK','Oceania'),
('Congo, the Democratic Republic of the','CD','COD','Africa'),
('Central African Republic','CF','CAF','Africa'),
('Congo','CG','COG','Africa'),
('Switzerland','CH','CHE','Europe'),
('Côte d''Ivoire','CI','CIV','Africa'),
('Cook Islands','CK','COK','Oceania'),
('Chile','CL','CHL','South America'),
('Cameroon','CM','CMR','Africa'),
('China','CN','CHN','Asia'),
('Colombia','CO','COL','South America'),
('Costa Rica','CR','CRI','Central America'),
('Cuba','CU','CUB','North America'),
('Cape Verde','CV','CPV','Africa'),
('Curaçao','CW','CUW','America'),
('Christmas Island','CX','CXR','Oceania'),
('Cyprus','CY','CYP','Asia'),
('Czech Republic','CZ','CZE','Europe'),
('Germany','DE','DEU','Europe'),
('Djibouti','DJ','DJI','Africa'),
('Denmark','DK','DNK','Europe'),
('Dominica','DM','DMA','North America'),
('Dominican Republic','DO','DOM','North America'),
('Algeria','DZ','DZA','Africa'),
('Ecuador','EC','ECU','South America'),
('Estonia','EE','EST','Europe'),
('Egypt','EG','EGY','Africa'),
('Western Sahara','EH','ESH','Africa'),
('Eritrea','ER','ERI','Africa'),
('Spain','ES','ESP','Europe'),
('Ethiopia','ET','ETH','Africa'),
('Finland','FI','FIN','Europe'),
('Fiji','FJ','FJI','Oceania'),
('Falkland Islands (Malvinas)','FK','FLK','South America'),
('Micronesia, Federated States of','FM','FSM','Oceania'),
('Faroe Islands','FO','FRO','Europe'),
('France','FR','FRA','Europe'),
('Gabon','GA','GAB','Africa'),
('United Kingdom','GB','GBR','Europe'),
('Grenada','GD','GRD','North America'),
('Georgia','GE','GEO','Asia'),
('French Guiana','GF','GUF','South America'),
('Guernsey','GG','GGY','Europe'),
('Ghana','GH','GHA','Africa'),
('Gibraltar','GI','GIB','Europe'),
('Greenland','GL','GRL','North America'),
('Gambia','GM','GMB','Africa'),
('Guinea','GN','GIN','Africa'),
('Guadeloupe','GP','GLP','North America'),
('Equatorial Guinea','GQ','GNQ','Africa'),
('Greece','GR','GRC','Europe'),
('South Georgia and the South Sandwich Islands','GS','SGS','Antarctica'),
('Guatemala','GT','GTM','Central America'),
('Guam','GU','GUM','Oceania'),
('Guinea-Bissau','GW','GNB','Africa'),
('Guyana','GY','GUY','South America'),
('Hong Kong','HK','HKG','Asia'),
('Heard Island and McDonald Islands','HM','HMD','Antarctica'),
('Honduras','HN','HND','Central America'),
('Croatia','HR','HRV','Europe'),
('Haiti','HT','HTI','North America'),
('Hungary','HU','HUN','Europe'),
('Indonesia','ID','IDN','Asia'),
('Ireland','IE','IRL','Europe'),
('Israel','IL','ISR','Asia'),
('Isle of Man','IM','IMN','Europe'),
('India','IN','IND','Asia'),
('British Indian Ocean Territory','IO','IOT','Africa'),
('Iraq','IQ','IRQ','Asia'),
('Iran, Islamic Republic of','IR','IRN','Asia'),
('Iceland','IS','ISL','Europe'),
('Italy','IT','ITA','Europe'),
('Jersey','JE','JEY','Europe'),
('Jamaica','JM','JAM','North America'),
('Jordan','JO','JOR','Asia'),
('Japan','JP','JPN','Asia'),
('Kenya','KE','KEN','Africa'),
('Kyrgyzstan','KG','KGZ','Asia'),
('Cambodia','KH','KHM','Asia'),
('Kiribati','KI','KIR','Oceania'),
('Comoros','KM','COM','Africa'),
('Saint Kitts and Nevis','KN','KNA','North America'),
('Korea, Democratic People''s Republic of','KP','PRK','Asia'),
('Korea, Republic of','KR','KOR','Asia'),
('Kuwait','KW','KWT','Asia'),
('Cayman Islands','KY','CYM','North America'),
('Kazakhstan','KZ','KAZ','Asia'),
('Lao People''s Democratic Republic','LA','LAO','Asia'),
('Lebanon','LB','LBN','Asia'),
('Saint Lucia','LC','LCA','North America'),
('Liechtenstein','LI','LIE','Europe'),
('Sri Lanka','LK','LKA','Asia'),
('Liberia','LR','LBR','Africa'),
('Lesotho','LS','LSO','Africa'),
('Lithuania','LT','LTU','Europe'),
('Luxembourg','LU','LUX','Europe'),
('Latvia','LV','LVA','Europe'),
('Libya','LY','LBY','Africa'),
('Morocco','MA','MAR','Africa'),
('Monaco','MC','MCO','Europe'),
('Moldova, Republic of','MD','MDA','Europe'),
('Montenegro','ME','MNE','Europe'),
('Saint Martin (French part)','MF','MAF','North America'),
('Madagascar','MG','MDG','Africa'),
('Marshall Islands','MH','MHL','Oceania'),
('Macedonia, the Former Yugoslav Republic of','MK','MKD','Europe'),
('Mali','ML','MLI','Africa'),
('Myanmar','MM','MMR','Asia'),
('Mongolia','MN','MNG','Asia'),
('Macao','MO','MAC','Asia'),
('Northern Mariana Islands','MP','MNP','Oceania'),
('Martinique','MQ','MTQ','North America'),
('Mauritania','MR','MRT','Africa'),
('Montserrat','MS','MSR','North America'),
('Malta','MT','MLT','Europe'),
('Mauritius','MU','MUS','Africa'),
('Maldives','MV','MDV','Asia'),
('Malawi','MW','MWI','Africa'),
('Mexico','MX','MEX','North America'),
('Malaysia','MY','MYS','Asia'),
('Mozambique','MZ','MOZ','Africa'),
('Namibia','NA','NAM','Africa'),
('New Caledonia','NC','NCL','Oceania'),
('Niger','NE','NER','Africa'),
('Norfolk Island','NF','NFK','Oceania'),
('Nigeria','NG','NGA','Africa'),
('Nicaragua','NI','NIC','Central America'),
('Netherlands','NL','NLD','Europe'),
('Norway','NO','NOR','Europe'),
('Nepal','NP','NPL','Asia'),
('Nauru','NR','NRU','Oceania'),
('Niue','NU','NIU','Oceania'),
('New Zealand','NZ','NZL','Oceania'),
('Oman','OM','OMN','Asia'),
('Panama','PA','PAN','Central America'),
('Peru','PE','PER','South America'),
('French Polynesia','PF','PYF','Oceania'),
('Papua New Guinea','PG','PNG','Oceania'),
('Philippines','PH','PHL','Asia'),
('Pakistan','PK','PAK','Asia'),
('Poland','PL','POL','Europe'),
('Saint Pierre and Miquelon','PM','SPM','North America'),
('Pitcairn','PN','PCN','Oceania'),
('Puerto Rico','PR','PRI','North America'),
('Palestine, State of','PS','PSE','Asia'),
('Portugal','PT','PRT','Europe'),
('Palau','PW','PLW','Oceania'),
('Paraguay','PY','PRY','South America'),
('Qatar','QA','QAT','Asia'),
('Réunion','RE','REU','Africa'),
('Romania','RO','ROU','Europe'),
('Serbia','RS','SRB','Europe'),
('Russian Federation','RU','RUS','Europe'),
('Rwanda','RW','RWA','Africa'),
('Saudi Arabia','SA','SAU','Asia'),
('Solomon Islands','SB','SLB','Oceania'),
('Seychelles','SC','SYC','Africa'),
('Sudan','SD','SDN','Africa'),
('Sweden','SE','SWE','Europe'),
('Singapore','SG','SGP','Asia'),
('Saint Helena, Ascension and Tristan da Cunha','SH','SHN','Africa'),
('Slovenia','SI','SVN','Europe'),
('Svalbard and Jan Mayen','SJ','SJM','Europe'),
('Slovakia','SK','SVK','Europe'),
('Sierra Leone','SL','SLE','Africa'),
('San Marino','SM','SMR','Europe'),
('Senegal','SN','SEN','Africa'),
('Somalia','SO','SOM','Africa'),
('Suriname','SR','SUR','South America'),
('South Sudan','SS','SSD','Africa'),
('Sao Tome and Principe','ST','STP','Africa'),
('El Salvador','SV','SLV','Central America'),
('Sint Maarten (Dutch part)','SX','SXM','America'),
('Syrian Arab Republic','SY','SYR','Asia'),
('Swaziland','SZ','SWZ','Africa'),
('Turks and Caicos Islands','TC','TCA','North America'),
('Chad','TD','TCD','Africa'),
('French Southern Territories','TF','ATF','Antarctica'),
('Togo','TG','TGO','Africa'),
('Thailand','TH','THA','Asia'),
('Tajikistan','TJ','TJK','Asia'),
('Tokelau','TK','TKL','Oceania'),
('Timor-Leste','TL','TLS','Asia'),
('Turkmenistan','TM','TKM','Asia'),
('Tunisia','TN','TUN','Africa'),
('Tonga','TO','TON','Oceania'),
('Turkey','TR','TUR','Asia'),
('Trinidad and Tobago','TT','TTO','North America'),
('Tuvalu','TV','TUV','Oceania'),
('Taiwan, Province of China','TW','TWN','Asia'),
('Tanzania, United Republic of','TZ','TZA','Africa'),
('Ukraine','UA','UKR','Europe'),
('Uganda','UG','UGA','Africa'),
('United Kingdom','UK','','Europe'),
('United States Minor Outlying Islands','UM','UMI','North America'),
('United States','US','USA','North America'),
('Uruguay','UY','URY','South America'),
('Uzbekistan','UZ','UZB','Asia'),
('Holy See (Vatican City State)','VA','VAT','Europe'),
('Saint Vincent and the Grenadines','VC','VCT','North America'),
('Venezuela, Bolivarian Republic of','VE','VEN','South America'),
('Virgin Islands, British','VG','VGB','North America'),
('Virgin Islands, U.S.','VI','VIR','North America'),
('Viet Nam','VN','VNM','Asia'),
('Vanuatu','VU','VUT','Oceania'),
('Wallis and Futuna','WF','WLF','Oceania'),
('Samoa','WS','WSM','Oceania'),
('Kosovo','XK','XKX','Europe'),
('Yemen','YE','YEM','Asia'),
('Mayotte','YT','MYT','Africa'),
('South Africa','ZA','ZAF','Africa'),
('Zambia','ZM','ZMB','Africa'),
('Zimbabwe','ZW','ZWE','Africa');
;#
UPDATE IzendaCity
	INNER JOIN IzendaCountryCode 
	ON IzendaCity.CountryCode = IzendaCountryCode.Code2
SET CountryName = IzendaCountryCode.Name, CountryCode3 = IzendaCountryCode.Code3